### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by quarthex** [AtomLinter/linter-oclitnt#3]
Why is this repository's name linter-oclitnt instead of linter-oclint?
I believe there is a typo here and the repository needs to be renamed.

**Comment by Arcanemagus** [comment]
I think a better question is why this repo exists at all, unless you want to implement this I think I'll just delete the repo since it appears it was just name-squatting in the first place 😒.

**Comment by Arcanemagus** [comment]
I've unpublished the package from APM for now. If somebody wants to implement this feel free to submit a PR and we can rename the repo properly then 😉.
